### ISSUE TITLE
Microsoft.ContainerService/managedClusters

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#128]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.ContainerService/managedClusters

**apiVersion** (i.e. 2019-04-01)
2020-09-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

None of these are changed and most of them are not defined in the template. osDiskSizeGB: is set to 0 which is the default value which is 128. This later is detected as change although both values should be the same. count is changed due to using autoscale and when cluster is updated nodes are brought online again. agentPools property is filled with the other pools as in previous version you could only define one pool in that property and the rest of pools you had to define via the sub RP. I am yet to test if you can now add all agent pools to agentPools property.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.ContainerService/managedClusters/akslz0001 [2020-09-01]
    - properties.addonProfiles.azurepolicy.config:

        version: "v2"

    - properties.addonProfiles.httpApplicationRouting.config:

        HTTPApplicationRoutingZoneName: "58a1c2dd9afe4d0343f55.westeurope.aksapp.io"

    - properties.addonProfiles.KubeDashboard:

        enabled: true

    - properties.autoScalerProfile:

        balance-similar-node-groups:      "false"
        expander:                         "random"
        max-empty-bulk-delete:            "10"
        max-graceful-termination-sec:     "600"
        max-total-unready-percentage:     "45"
        new-pod-scale-up-delay:           "0s"
        ok-total-unready-count:           "3"
        scale-down-delay-after-add:       "10m"
        scale-down-delay-after-delete:    "10s"
        scale-down-delay-after-failure:   "3m"
        scale-down-unneeded-time:         "10m"
        scale-down-unready-time:          "20m"
        scale-down-utilization-threshold: "0.5"
        scan-interval:                    "10s"
        skip-nodes-with-local-storage:    "false"
        skip-nodes-with-system-pods:      "true"

    - properties.networkProfile.loadBalancerProfile.effectiveOutboundIPs: [
        0:

          id: "/subscriptions/<sub id>/resourceGroups/lz-k8s-1-nodes/providers/Microsoft.Network/publicIPAddresses/64aae422-45db-4508-91f1-7825a6a80a98"

      ]
    - sku:

        name: "Basic"
        tier: "Free"

[
      ~ 0:

        - mode:       "User"
        - osDiskType: "Managed"

      - 1:

          availabilityZones: [
            0: "1"
            1: "2"
          ]
          count:               1
          enableAutoScaling:   true
          enableNodePublicIP:  false
          maxCount:            4
          maxPods:             115
          minCount:            1
          mode:                "User"
          name:                "pool3"
          orchestratorVersion: "1.17.9"
          osDiskSizeGB:        100
          osDiskType:          "Managed"
          osType:              "Linux"
          type:                "VirtualMachineScaleSets"
          vmSize:              "Standard_DS2_v2"
          vnetSubnetID:        "/subscriptions<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"

      - 2:

          count:               1
          enableAutoScaling:   false
          enableNodePublicIP:  false
          maxPods:             110
          mode:                "User"
          name:                "pool5"
          orchestratorVersion: "1.17.9"
          osDiskSizeGB:        128
          osDiskType:          "Managed"
          osType:              "Windows"
          type:                "VirtualMachineScaleSets"
          vmSize:              "Standard_DS2_v2"
          vnetSubnetID:        "/subscriptions/<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"

      ]

  ~ Microsoft.ContainerService/managedClusters/akslz0001/agentPools/pool1 [2020-09-01]
    - properties.mode:         "User"
    - properties.osDiskType:   "Managed"
    - properties.vnetSubnetID: "/subscriptions/<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"

  ~ Microsoft.ContainerService/managedClusters/akslz0001/agentPools/pool3 [2020-09-01]
    - properties.mode:         "User"
    - properties.osDiskType:   "Managed"
    - properties.vnetSubnetID: "/subscriptions/<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"
    ~ properties.count:        1 => 3

  ~ Microsoft.ContainerService/managedClusters/akslz0001/agentPools/pool5 [2020-09-01]
    - properties.mode:         "User"
    - properties.osDiskType:   "Managed"
    - properties.vnetSubnetID: "/subscriptions/<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"
    ~ properties.osDiskSizeGB: 128 => 0

```

**Additional context**

**Comment by slavizh** [comment]
BTW also if you set properties.count to 0 the change will look like 2 => 0 but actually the node count does not change. 0 nodes can be applied only upon first creation when 0 is passed after creation it does not change the count.

**Comment by slavizh** [comment]
There are some additional issues when you have some node pools removed from the configuration but still present on the managed cluster. Then what-if gets really confused and shows nonsense like below. pool1, pool5, pool3 are defined in the configuration pool11 and pool12 are not but present on the cluster.



```
  ~ Microsoft.ContainerService/managedClusters/akslz0001 [2020-09-01]
    - properties.addonProfiles.httpApplicationRouting.config:

        HTTPApplicationRoutingZoneName: "58a1c2dd9afe4d068sds4c.westeurope.aksapp.io"

    - properties.addonProfiles.KubeDashboard:

        enabled: true

    - properties.enablePodSecurityPolicy: false
    - properties.networkProfile.loadBalancerProfile.effectiveOutboundIPs: [
        0:

          id: "/subscriptions/<sub id>/resourceGroups/lz-k8s-1-nodes/providers/Microsoft.Network/publicIPAddresses/64aae422-45db-4508-91f1-7825a6a80a98"

      ]
[
      ~ 1:

        - maxCount:          3
        - minCount:          1

        ~ enableAutoScaling: true => false
        ~ maxPods:           120 => 110
        ~ name:              "pool11" => "pool5"
        ~ osDiskSizeGB:      100 => 0
        ~ osType:            "Linux" => "Windows"
      ~ 2:

        - count:    1
        + availabilityZones: [
            0: "1"
            1: "2"
          ]
        + nodeLabels:

            stan: "value1"

        ~ maxCount: 3 => 4
        ~ maxPods:  120 => 115
        ~ name:     "pool12" => "pool3"
     - 3:

          availabilityZones: [
            0: "1"
            1: "2"
          ]
          count:                1
          enableAutoScaling:    true
          enableNodePublicIP:   false
          maxCount:             4
          maxPods:              115
          minCount:             1
          mode:                 "User"
          name:                 "pool3"
          nodeLabels.stan:      "value1"
          orchestratorVersion:  "1.17.9"
          osDiskSizeGB:         100
          osDiskType:           "Managed"
          osType:               "Linux"
          type:                 "VirtualMachineScaleSets"
          vmSize:               "Standard_DS2_v2"
          vnetSubnetID:         "/subscriptions/<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"
    - 4:

          count:                1
          enableAutoScaling:    false
          enableNodePublicIP:   false
          maxPods:              110
          mode:                 "User"
          name:                 "pool5"
          orchestratorVersion:  "1.17.9"
          osDiskSizeGB:         128
          osDiskType:           "Managed"
          osType:               "Windows"
          type:                 "VirtualMachineScaleSets"
          vmSize:               "Standard_DS2_v2"
          vnetSubnetID:         "/subscriptions/<sub id>/resourceGroups/lz-aks-vnet/providers/Microsoft.Network/virtualNetworks/vnet001/subnets/default"

      ]

```

**Comment by slavizh** [comment]
Seems like the configuration needs to be in particular order ( I guess alphabetical) in order what-if to manage to work properly as the problem exists even if the not defined agent pools in the configuration are also deleted from the cluster.

**Comment by slavizh** [comment]
Seems also the AKS team hasn't fixed the problem of defining all agent pools in agentPoolProfiles property which means that every time when what-if is run you will see agent pools removed from that property but they are actually not removed just defined as sub-resource.

**Comment by slavizh** [comment]
Seems that tonight there was some update on the RP and there are now more noise that are shown like 


```
  ~ Microsoft.ContainerService/managedClusters/akslz0001 [2020-09-01]
    - properties.addonProfiles.aciConnectorLinux.identity:

        clientId:   "<guid>"
        objectId:   "<guid>"
        resourceId: "/subscriptions/<guid>/resourcegroups/lz-k8s-1-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aciconnectorlinux-akslz0001"

    - properties.addonProfiles.azurepolicy.identity:

        clientId:   "<guid>"
        objectId:   "<guid>"
        resourceId: "/subscriptions/<guid>/resourcegroups/lz-k8s-1-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurepolicy-akslz0001"

    - properties.addonProfiles.httpApplicationRouting.config:

        HTTPApplicationRoutingZoneName: "5d086df9ef8643c434xb85.westeurope.aksapp.io"

    - properties.addonProfiles.httpApplicationRouting.identity:

        clientId:   "<guid>"
        objectId:   "<guid>"
        resourceId: "/subscriptions/<guid>/resourcegroups/lz-k8s-1-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/httpapplicationrouting-akslz0001"

    - properties.addonProfiles.KubeDashboard:

        enabled:             true
        identity.clientId:   "<guid>"
        identity.objectId:   "<guid>"
        identity.resourceId: "/subscriptions/<guid>/resourcegroups/lz-k8s-1-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/kubedashboard-akslz0001"

    - properties.addonProfiles.omsagent.identity:

        clientId:   "<guid>"
        objectId:   "<guid>"
        resourceId: "/subscriptions/<guid>/resourcegroups/lz-k8s-1-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent-akslz0001"

    - properties.identityProfile:

        kubeletidentity.clientId:   "<guid>"
        kubeletidentity.objectId:   "<guid>"
        kubeletidentity.resourceId: "/subscriptions/<guid>/resourcegroups/lz-k8s-1-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/akslz0001-agentpool"



```

**Comment by slavizh** [comment]
Seems now there are even more updates on the RP and powerState is shown on agentPools and managedClusters

```
  ~ Microsoft.ContainerService/managedClusters/akslz0001/agentPools/pool6 [2020-09-01]
    - properties.powerState:

        code: "Running"
```

**Comment by alex-frankel** [comment]
@detienne20 - do you know what week this went out?

**Comment by detienne20** [comment]
w48

**Comment by alex-frankel** [comment]
@detienne20  - can you check if this has been deployed? If so, we can close the issue

**Comment by carlin-q-scott** [comment]
Default values are still showing up in what-if for identityProfile. It says it will remove the profile, but thankfully it doesn't.

**Comment by ryanthedev** [comment]
Still all busted.  Almost had a heart attack when I saw node pools were going to be removed.

az cli version
```
{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.3"
  }
}
```

**Comment by bonddim** [comment]
Almost 3 years and with each API update we have more and more noise on defaults and deleting node pools

**Comment by slavizh** [comment]
I think the whole initiative around what-if feature has failed. Without someone from higher management like Scott Guthrie picks this and makes sure that teams are compliant with this I think it will just get worse. Other options are what-if to be deprecated as it is not working properly anyway or take another approach where resource provider teams do not have to comply in order what-if to work.

**Comment by dosmanak** [comment]
We try to migrate from terraform to bicep and this is surprising disadvantage!

**Comment by bonddim** [comment]
> We try to migrate from terraform to bicep and this is surprising disadvantage!

I migrated from bicep to terraform because of this

**Comment by rezarms** [comment]
When it comes to AKS and managed identity, the what-if is completely useless.
```
- properties.identityProfile:

        kubeletidentity.clientId:   "guid"
        kubeletidentity.objectId:   "guid"
        kubeletidentity.resourceId: "resourceId
```

`Bicep CLI version 0.37.4 (27cc8db2ed)`

It always shows the identityProfile will be deleted.
It made me thinking migrating to terraform.
