### ISSUE TITLE
Microsoft.Web/staticSites@2024-04-01 noise report

### ISSUE THREAD

**Issue by victorfrye** [Azure/arm-template-whatif#390]
## Describe the noise

**Resource type**
Microsoft.Web/staticSites

**apiVersion** (i.e. 2019-04-01)
2024-04-01

**Client (PowerShell, Azure CLI, or API)**
azure/bicep-deploy GH action

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```bicep
param projectName string
param appName string
param appRepo string

param location string = resourceGroup().location

resource swaApp 'Microsoft.Web/staticSites@2024-04-01' = {
  name: 'stapp-${appName}'
  location: location
  sku: {
    name: 'Free'
    tier: 'Free'
  }
  tags: {
    Project: projectName
  }
  properties: {
    repositoryUrl: 'https://github.com/${appRepo}'
    branch: 'main'
    stagingEnvironmentPolicy: 'Enabled'
    allowConfigFileUpdates: true
    provider: 'GitHub'
    enterpriseGradeCdnStatus: 'Disabled'
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

I expected no noise since the template has not been modified since the resources were deployed.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.Web/staticSites/stapp-${appName} [2024-04-01]
    - properties.areStaticSitesDistributedBackendsEnabled: false
    - properties.deploymentAuthPolicy:"DeploymentToken"
    - properties.stableInboundIP:"20.106.1.32"
    - properties.trafficSplitting:

        environmentDistribution.default: 100
```

**Additional context**
