### ISSUE TITLE
Microsoft.Authorization/policyAssignments

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#68]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Authorization/policyAssignments

**apiVersion** (i.e. 2019-04-01)
2019-01-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes to the SKU property. 

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
Scope: /subscriptions/<subscription ID>

  ~ Microsoft.Authorization/policyAssignments/add-vms-to-backup-1 [2019-01-01]
    - sku:

        name: "A0"
        tier: "Free"


```

**Additional context**
